version: "3.9"

services:
  app:
    build: .
    container_name: kodeks_admin_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: kodeks_admin_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kodeks_admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
