version: "3.9"

services:
  app:
    build: .
    container_name: kodeks_admin_app
    ports:
      - "8000:8000"  # FastAPI на 8000 порту
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@host.docker.internal:5432/kodeks_admin
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped